matrix:
  include:
    - os: osx
      osx_image: xcode8.2
    - os: linux
      dist: trusty
      sudo: required

language: c

addons:
  apt:
    packages:
      - cmake
      - make
      - gcc-4.8
      - g++-4.8
      - qt5-default
      - libglew-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then      scripts/install_mac.sh   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo scripts/install_linux.sh ; fi

install:
  - cmake .
