matrix:
  include:
    - os: osx
      osx_image: xcode8.2
    - os: linux
      dist: trusty
      sudo: false

language: c

compiler:
  - clang
  - gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi

install:
  - cmake .
